project:
  type: website
  output-dir: docs

website:
  title: "R Portfolio Summer 2025"
  navbar:
    right:
      - portfolio.qmd
      - about.qmd
      - icon: github
        href: https://github.com/Briggy12
      - icon: twitter
        href: https://twitter.com/MattCrumpLab
format:
  html:
    theme: solar
    css: styles.css

editor: visual

