---
title: "Police Sentiment Scores | City of Chicago Dataset Project"
author: "Briggy12"
date: "2025.8.7"
categories: [data_science,general]
---

## My Project

Quick Links:

-   [data.gov](ttps://catalog.data.gov/dataset/police-sentiment-scores "Links to data.gov's webpage featuring the dataset used for this project") page ([https://catalog.data.gov/dataset/police-sentiment-scores](ttps://catalog.data.gov/dataset/police-sentiment-scores))

-   original source page [here](ttps://data.cityofchicago.org/Public-Safety/Police-Sentiment-Scores/28me-84fj/about_data "The original posting of the dataset "Police Sentiment Scores" for Chicago.") ([https://data.cityofchicago.org/Public-Safety/Police-Sentiment-Scores/28me-84fj/about_data](ttps://data.cityofchicago.org/Public-Safety/Police-Sentiment-Scores/28me-84fj/about_data)).

### yea

and then here I'll give a description of the project

### Perhaps

When looking for a dataset, I wanted to dive into something more political and within my interests. I found this dataset on [data.gov](ttps://catalog.data.gov/dataset/police-sentiment-scores "Links to data.gov's webpage featuring the dataset used for this project") ([https://catalog.data.gov/dataset/police-sentiment-scores](ttps://catalog.data.gov/dataset/police-sentiment-scores)) which showed data on the "trust" of participants with the police. The "trust" was a rating of 1-10 from a variety of demographics spanning 22 districts within Chicago.

Mention interest and also survey methodology

### Then the actual nitty-gritty.

So here I'll give a breakdown of my first question and my process for going about answering it. Underneath, probably I will caption the code for accessibility and to have a running record of what I did. It also makes it more accessible.

Ideally, I'd like 2-3 major questions and I'll answer them all here in a similar format under this header.

Below, you'll find the code that I ran in R to create models from this data set.

```{r}
install.packages("ggplot2")
library(ggplot2)

PSS <- read.csv("Police_Sentiment_Scores.csv")

ggplot(data = PSS, aes(x=T_SEX_MALE)) + geom_histogram()
```

### Maybe then the closer/conclusion?

I want to check back with my previous workshops that involved EDA and see what the format was there to make this more professional and mirror the academia process for it. It makes it more accessible and preps me for whatever's to come in the future that does this.
